jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.3'
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: jx-variables
      uses: docker://ghcr.io/jenkins-x/jx-boot:latest
      with:
        args: >
          -c "git config --global --add safe.directory /github/workspace; jx gitops variables"
        entrypoint: /bin/sh
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: build-make-linux
      uses: docker://golang:1.24.4
      with:
        args: -c "make linux"
        entrypoint: /bin/sh
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: build-make-test
      uses: docker://golang:1.24.4
      with:
        args: -c "make test"
        entrypoint: /bin/sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-preview
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.event.number }}
on:
  pull_request:
    branches:
    - main
    - master
